## 행렬의 내적

      벡터나 행렬은 원소별로 계산함
    
       행렬도 내부의 벡터의 원소가 같을 때만 각 원소별로 곱한 후에 합산을 해서 내적을 구함 

In [1]:
import numpy as np

In [2]:
X = np.array([1,2])

In [3]:
X.shape

(2,)

In [4]:
W = np.array([[1,3,5],[2,4,6]])

In [5]:
W

array([[1, 3, 5],
       [2, 4, 6]])

In [6]:
W.shape

(2, 3)

In [7]:
Y = np.dot(X,W)

In [8]:
Y

array([ 5, 11, 17])

## 원소별로 개수가 다르면 예외 발생 

In [14]:
try :
    Z = np.dot(W,X)
except Exception as e :
    print(e)

shapes (2,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)


In [15]:
X1= [1,2,3]

In [16]:
Z = np.dot(W,X1)

In [17]:
Z

array([22, 28])

In [18]:
Z.shape

(2,)