In [1]:
import tensorflow as tf

In [3]:
import numpy as np

In [4]:
data = np.array([[2,81], [4, 93], [6, 91], [8,97] ])

In [5]:
data

array([[ 2, 81],
       [ 4, 93],
       [ 6, 91],
       [ 8, 97]])

## 독립변수

In [10]:
x_data = data[:, 0]

In [11]:
x_data

array([2, 4, 6, 8])

## 종속변수 : 정답

In [12]:
y_data = data[:,1]

In [13]:
y_data

array([81, 93, 91, 97])

## 기울기, 편향 등 가중치

In [16]:
a = tf.Variable(tf.random_uniform([1], 0, 10, dtype=tf.float64, seed=0))

In [18]:
b = tf.Variable(tf.random_uniform([1], 0.,100., dtype = tf.float64, seed=0))

## 실제 계산값을 연산자

In [22]:
y = a * x_data + b

### 텐서플로우 함수로 표시

In [25]:
y_ = tf.add(tf.multiply(a, x_data), b)

In [23]:
y

<tf.Tensor 'add_4:0' shape=(4,) dtype=float64>

In [26]:
y_

<tf.Tensor 'Add_5:0' shape=(4,) dtype=float64>

## 평균제곱근 오차 함수 

In [24]:
rmse = tf.sqrt(tf.reduce_mean(tf.square(y - y_data)))

## 학습률

In [27]:
learning_rate = 0.1

## 경사하강

In [28]:
gradient_decent = tf.train.GradientDescentOptimizer(learning_rate).minimize(rmse)

In [30]:
with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001) :
        sess.run(gradient_decent)
        if step % 100 == 0 :
            print(" Epoch : %.f, RSME = %.04f,  기울기 a= %.4f, y절편 : b = %.4f" % (step, sess.run(rmse), sess.run(a), sess.run(b)))

 Epoch : 0, RSME = 30.2139,  기울기 a= 7.5235, y절편 : b = 80.5984
 Epoch : 100, RSME = 2.8860,  기울기 a= 2.2299, y절편 : b = 79.4181
 Epoch : 200, RSME = 2.8826,  기울기 a= 2.2601, y절편 : b = 79.2379
 Epoch : 300, RSME = 2.8815,  기울기 a= 2.2773, y절편 : b = 79.1353
 Epoch : 400, RSME = 2.8811,  기울기 a= 2.2871, y절편 : b = 79.0770
 Epoch : 500, RSME = 2.8810,  기울기 a= 2.2927, y절편 : b = 79.0438
 Epoch : 600, RSME = 2.8810,  기울기 a= 2.2958, y절편 : b = 79.0249
 Epoch : 700, RSME = 2.8810,  기울기 a= 2.2976, y절편 : b = 79.0142
 Epoch : 800, RSME = 2.8810,  기울기 a= 2.2987, y절편 : b = 79.0081
 Epoch : 900, RSME = 2.8810,  기울기 a= 2.2992, y절편 : b = 79.0046
 Epoch : 1000, RSME = 2.8810,  기울기 a= 2.2996, y절편 : b = 79.0026
 Epoch : 1100, RSME = 2.8810,  기울기 a= 2.2998, y절편 : b = 79.0015
 Epoch : 1200, RSME = 2.8810,  기울기 a= 2.2999, y절편 : b = 79.0008
 Epoch : 1300, RSME = 2.8810,  기울기 a= 2.2999, y절편 : b = 79.0005
 Epoch : 1400, RSME = 2.8810,  기울기 a= 2.3000, y절편 : b = 79.0003
 Epoch : 1500, RSME = 2.8810,  기울기 a= 2.3000, y절편 :